import type { MenuCategory } from "./types";

export const menuData: MenuCategory[] = [
  {
    name: "Appetizers",
    emoji: "🥗",
    items: [
      {
        name: "Bruschetta",
        price: 9.99,
        description: "Toasted bread, fresh tomatoes, basil, garlic, olive oil",
        allergens: ["gluten"],
        tags: ["vegetarian", "vegan"],
      },
      {
        name: "Caesar Salad",
        price: 12.99,
        description: "Romaine lettuce, parmesan, croutons, house caesar dressing",
        allergens: ["gluten", "dairy", "eggs"],
        tags: ["vegetarian"],
      },
      {
        name: "Calamari Fritti",
        price: 13.99,
        description: "Lightly breaded calamari, marinara dipping sauce",
        allergens: ["gluten", "seafood"],
        tags: [],
      },
      {
        name: "Minestrone Soup",
        price: 8.99,
        description: "Seasonal vegetables, cannellini beans, pasta, tomato broth",
        allergens: ["gluten"],
        tags: ["vegetarian", "vegan"],
      },
    ],
  },
  {
    name: "Pasta",
    emoji: "🍝",
    items: [
      {
        name: "Spaghetti Carbonara",
        price: 16.99,
        description: "Spaghetti, pancetta, eggs, parmesan, black pepper",
        allergens: ["gluten", "dairy", "eggs"],
        tags: [],
      },
      {
        name: "Penne Arrabbiata",
        price: 14.99,
        description: "Penne, spicy tomato sauce, garlic, fresh basil",
        allergens: ["gluten"],
        tags: ["vegetarian", "vegan"],
      },
      {
        name: "Fettuccine Alfredo",
        price: 15.99,
        description: "Fettuccine, butter, heavy cream, parmesan",
        allergens: ["gluten", "dairy"],
        tags: ["vegetarian"],
      },
      {
        name: "Lasagna Bolognese",
        price: 17.99,
        description: "Layers of pasta, beef ragu, bechamel, mozzarella",
        allergens: ["gluten", "dairy", "eggs"],
        tags: [],
      },
      {
        name: "Mushroom Risotto",
        price: 16.99,
        description: "Arborio rice, mixed mushrooms, parmesan, white wine",
        allergens: ["dairy"],
        tags: ["vegetarian", "gluten-free"],
      },
    ],
  },
  {
    name: "Mains",
    emoji: "🍽️",
    items: [
      {
        name: "Chicken Parmesan",
        price: 19.99,
        description: "Breaded chicken breast, marinara sauce, melted mozzarella",
        allergens: ["gluten", "dairy", "eggs"],
        tags: [],
        note: "Served with spaghetti or salad",
      },
      {
        name: "Grilled Salmon",
        price: 24.99,
        description: "Atlantic salmon fillet, lemon butter sauce, seasonal vegetables",
        allergens: ["fish", "dairy"],
        tags: ["gluten-free"],
      },
      {
        name: "Eggplant Parmesan",
        price: 17.99,
        description: "Breaded eggplant, marinara, mozzarella, fresh basil",
        allergens: ["gluten", "dairy", "eggs"],
        tags: ["vegetarian"],
        note: "Served with pasta or salad",
      },
      {
        name: "Veal Piccata",
        price: 22.99,
        description: "Veal cutlets, lemon caper butter sauce, angel hair pasta",
        allergens: ["gluten", "dairy"],
        tags: [],
      },
      {
        name: "Shrimp Scampi",
        price: 21.99,
        description: "Jumbo shrimp, garlic butter, white wine, linguine",
        allergens: ["shellfish", "gluten", "dairy"],
        tags: [],
      },
    ],
  },
  {
    name: "Desserts",
    emoji: "🍮",
    items: [
      {
        name: "Tiramisu",
        price: 8.99,
        description: "Espresso soaked ladyfingers, mascarpone cream, cocoa",
        allergens: ["gluten", "dairy", "eggs"],
        tags: ["vegetarian"],
      },
      {
        name: "Panna Cotta",
        price: 7.99,
        description: "Vanilla bean cream, fresh berry compote",
        allergens: ["dairy"],
        tags: ["vegetarian", "gluten-free"],
      },
      {
        name: "Cannoli",
        price: 6.99,
        description: "Crispy pastry shell, sweet ricotta filling, chocolate chips",
        allergens: ["gluten", "dairy"],
        tags: ["vegetarian"],
      },
      {
        name: "Gelato",
        price: 5.99,
        description: "Choice of vanilla, chocolate, pistachio, or strawberry",
        allergens: ["dairy"],
        tags: ["vegetarian", "gluten-free"],
      },
      {
        name: "Chocolate Lava Cake",
        price: 9.99,
        description: "Warm chocolate cake, molten center, vanilla gelato",
        allergens: ["gluten", "dairy", "eggs"],
        tags: ["vegetarian"],
      },
    ],
  },
  {
    name: "Drinks",
    emoji: "🍷",
    items: [
      {
        name: "San Pellegrino Sparkling Water",
        price: 3.99,
        description: "Classic Italian sparkling mineral water",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
      {
        name: "Still Water",
        price: 2.99,
        description: "Still mineral water",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
      {
        name: "Italian Soda",
        price: 4.99,
        description: "Blood orange, lemon, or raspberry",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
      {
        name: "Espresso",
        price: 3.49,
        description: "Rich Italian espresso shot",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
      {
        name: "Cappuccino",
        price: 4.99,
        description: "Espresso with steamed milk foam",
        allergens: ["dairy"],
        tags: ["vegetarian"],
      },
      {
        name: "Prosecco",
        price: 9.99,
        description: "Italian sparkling wine, by the glass",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
      {
        name: "House Red Wine",
        price: 8.99,
        description: "Curated Italian red, by the glass",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
      {
        name: "House White Wine",
        price: 8.99,
        description: "Crisp Italian white, by the glass",
        allergens: [],
        tags: ["vegetarian", "vegan", "gluten-free"],
      },
    ],
  },
];
